using Microsoft.Extensions.Logging;
using System.Net.Http.Json;
using System.Text;

namespace DotNetElements.Extensions.Icons;

internal partial class CodiconsFontGenerator
{
    private readonly HttpClient httpClient;
    private readonly ILogger<CodiconsFontGenerator> logger;

    public CodiconsFontGenerator(HttpClient httpClient, ILogger<CodiconsFontGenerator> logger)
    {
        this.httpClient = httpClient;
        this.logger = logger;
    }

    public async Task Run()
    {
        IReadOnlyList<Codicon>? iconInfo = await GetIconInfoAsync();

        if (iconInfo is null)
            return;

        await WriteToFileAsync(iconInfo);

        logger.LogInformation("Generated Codicon icons");
    }

    private async Task<IReadOnlyList<Codicon>?> GetIconInfoAsync()
    {
        Dictionary<string, int>? codepointInfo = await httpClient.GetFromJsonAsync<Dictionary<string, int>>("https://raw.githubusercontent.com/microsoft/vscode-codicons/main/src/template/mapping.json");

        if (codepointInfo is null)
        {
            logger.LogError("Failed to get available icons from Github! (Failed to fetch codepoint info.)");
            return null;
        }

        List<Codicon> iconSet = [];

        foreach ((string name, int unicode) in codepointInfo)
        {
            iconSet.Add(new Codicon(name, unicode.ToString()));
        }

        return iconSet;
    }

    private static async Task WriteToFileAsync(IReadOnlyList<Codicon> iconInfo)
    {
        StringBuilder resultBuilder = new();
        resultBuilder.AppendLine(fileHeader);

        StringBuilder iconBuilder = new();

        foreach (Codicon icon in iconInfo)
        {
            string varName = icon.Id!.ConvertDashToPascalCase();

            iconBuilder.AppendLine($"		{varName} = {$"{icon.Unicode}"},");
        }

        resultBuilder.Append(iconBuilder);
        resultBuilder.Append(fileFooter);

        await File.WriteAllTextAsync("CodiconIcons.cs", resultBuilder.ToString());
    }

    private const string fileHeader =
    """
    //----------------------
    // <auto-generated>
    //     Generated by the DotNetElements.Extensions.Icons CodiconsFontGenerator. DO NOT EDIT!
    //     source: CodiconsFontGenerator.cs
    // </auto-generated>
    //----------------------
    
    namespace DotNetElements.Extensions.Icons;
    
    public static partial class Icons
    {
    	public enum Codicon
    	{
            None = 0,
    """;

    private const string fileFooter =
    """
        }
    }
        
    """;

    private record Codicon(string Id, string Unicode);
}
