using Microsoft.Extensions.Logging;
using System.Text;

namespace DotNetElements.Extensions.Icons;


internal partial class MaterialIconsFontGenerator
{
    private readonly HttpClient httpClient;
    private readonly ILogger<MaterialIconsFontGenerator> logger;

    public MaterialIconsFontGenerator(HttpClient httpClient, ILogger<MaterialIconsFontGenerator> logger)
    {
        this.httpClient = httpClient;
        this.logger = logger;
    }

    public async Task Run()
    {
        IReadOnlyList<MaterialIcon>? iconInfo = await GetIconInfoAsync();

        if (iconInfo is null)
            return;

        await WriteToFileAsync(iconInfo);

        logger.LogInformation("Generated Material icons");
    }

    private async Task<IReadOnlyList<MaterialIcon>?> GetIconInfoAsync()
    {
        string codepointInfo = await httpClient.GetStringAsync("https://raw.githubusercontent.com/google/material-design-icons/master/variablefont/MaterialSymbolsRounded%5BFILL%2CGRAD%2Copsz%2Cwght%5D.codepoints");

        if (string.IsNullOrEmpty(codepointInfo))
        {
            logger.LogError("Failed to get available icons from Github! (Failed to fetch codepoint info.)");
            return null;
        }

        List<MaterialIcon> iconSet = [];

        foreach (string codepointInfoLine in codepointInfo.Split('\n'))
        {
            string[] glyphInfo = codepointInfoLine.Split(" ");

            if (glyphInfo.Length == 1 & glyphInfo[0] == "")
                continue;

            if (glyphInfo.Length != 2)
            {
                logger.LogError("Failed to get available icons from Github! (Failed to read codepoint info.)");
                return null;
            }

            iconSet.Add(new MaterialIcon(glyphInfo[0], glyphInfo[1]));
        }

        return iconSet;
    }

    private async Task WriteToFileAsync(IReadOnlyList<MaterialIcon> iconInfo)
    {
        StringBuilder resultBuilder = new();
        resultBuilder.AppendLine(fileHeader);

        StringBuilder iconBuilder = new();

        StringBuilder iconDictionaryBuilder = new();
        iconDictionaryBuilder.AppendLine(iconDictionaryHeader);

        foreach (MaterialIcon icon in iconInfo)
        {
            string varName = icon.Id!.ConvertSnakeToPascalCase();

            iconBuilder.AppendLine($"		{varName},");

            iconDictionaryBuilder.AppendLine($"            {{ {varName}, \"\\u{icon.Unicode}\" }},");
        }

        resultBuilder.Append(iconBuilder);
        resultBuilder.Append(iconDictionaryHeader);
        resultBuilder.Append(iconDictionaryBuilder);
        resultBuilder.Append(fileFooter);

        await File.WriteAllTextAsync("MaterialIcons.cs", resultBuilder.ToString());
    }

    private const string fileHeader =
    """
	//----------------------
	// <auto-generated>
	//     Generated by the DotNetElements.Extensions.Icons MaterialIconsFontGenerator. DO NOT EDIT!
	//     source: MaterialIconsFontGenerator.cs
	// </auto-generated>
	//----------------------

	namespace DotNetElements.Extensions.Icons;

	public static partial class Icons
	{
		public enum Material
		{
	""";

    private const string iconDictionaryHeader =
    """
        }
        
        public static class MaterialIconsExtensions
        {
            private readonly static Dictionary<Material, string> unicodeMap = new()
            {
    """;

    private const string fileFooter =
    """
            };
            
            public static string ToUnicode(this Material materialIcon)
            {
                return unicodeMap[materialIcon];
            }
        }
    }
        
    """;

    private record MaterialIcon(string Id, string Unicode);
}
