<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.2" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.2" />
		<PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="9.0.2" />
		<PackageReference Include="NCronJob" Version="4.3.4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DotNetElements.AppFramework.Abstractions\DotNetElements.AppFramework.Abstractions.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Entity\" />
	</ItemGroup>

</Project>
