<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>
	
	<PropertyGroup>
		<AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FluentAssertions" Version="8.0.1" />
		<PackageReference Include="FluentAssertions.Analyzers" Version="0.34.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.2" />
		<PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" Version="9.2.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
		<PackageReference Include="MSTest.TestAdapter" Version="3.8.0" />
		<PackageReference Include="MSTest.TestFramework" Version="3.8.0" />
		<PackageReference Include="coverlet.collector" Version="6.0.4">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\DotNetElements.Core\DotNetElements.Core.Old.csproj" />
	</ItemGroup>

</Project>
